"""add_notified_deals

Revision ID: 118f7c7dd37d
Revises: bafa7fdf8eda
Create Date: 2026-05-02 12:24:56.144469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118f7c7dd37d'
down_revision: Union[str, Sequence[str], None] = 'bafa7fdf8eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notified_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notified_deals')
    # ### end Alembic commands ###
