"""add_opencritic_and_limits

Revision ID: a9f454f7c0de
Revises: c29d0ffb1056
Create Date: 2026-05-02 13:01:25.670145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f454f7c0de'
down_revision: Union[str, Sequence[str], None] = 'c29d0ffb1056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=True),
    sa.Column('reset_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    with op.batch_alter_table('game_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critic_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('critic_tier', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_score_sync', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_cache', schema=None) as batch_op:
        batch_op.drop_column('last_score_sync')
        batch_op.drop_column('critic_tier')
        batch_op.drop_column('critic_score')

    op.drop_table('api_limits')
    # ### end Alembic commands ###
