"""add_ops_metrics

Revision ID: b851ce9ca1e2
Revises: 66122c48e4c6
Create Date: 2026-05-02 13:28:21.995918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b851ce9ca1e2'
down_revision: Union[str, Sequence[str], None] = '66122c48e4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_limits_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=True),
    sa.Column('reset_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('game_cache_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('platforms', sa.String(), nullable=True),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('store_link', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('platform_type', sa.String(), nullable=True),
    sa.Column('monetization_tags', sa.String(), nullable=True),
    sa.Column('is_limited_time', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('critic_score', sa.Integer(), nullable=True),
    sa.Column('critic_tier', sa.String(), nullable=True),
    sa.Column('last_score_sync', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('game_cache_v2', schema=None) as batch_op:
        batch_op.create_index('idx_expiry', ['expiry_date'], unique=False)
        batch_op.create_index('idx_game_type', ['game_type'], unique=False)
        batch_op.create_index('idx_ltf', ['is_limited_time'], unique=False)
        batch_op.create_index('idx_platform_type', ['platform_type'], unique=False)
        batch_op.create_index('idx_release_date', ['release_date'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)
        batch_op.create_index('idx_title', ['title'], unique=False)

    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('rows_affected', sa.Integer(), nullable=True),
    sa.Column('db_size_before', sa.Float(), nullable=True),
    sa.Column('db_size_after', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_tokens_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('items_synced', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('oauth_tokens')
    op.drop_table('game_cache')
    op.drop_table('api_limits')
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_column('platform_switch')
        batch_op.drop_column('platform_ps')
        batch_op.drop_column('platform_pc')
        batch_op.drop_column('platform_xbox')
        batch_op.drop_column('platform_mobile')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_mobile', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('platform_xbox', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('platform_pc', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('platform_ps', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('platform_switch', sa.BOOLEAN(), nullable=True))

    op.create_table('api_limits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_name', sa.VARCHAR(), nullable=False),
    sa.Column('call_count', sa.INTEGER(), nullable=True),
    sa.Column('reset_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('game_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('platforms', sa.VARCHAR(), nullable=True),
    sa.Column('original_price', sa.INTEGER(), nullable=True),
    sa.Column('current_price', sa.INTEGER(), nullable=True),
    sa.Column('release_date', sa.DATETIME(), nullable=True),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('store_link', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('source_name', sa.VARCHAR(), nullable=False),
    sa.Column('game_type', sa.VARCHAR(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('critic_score', sa.INTEGER(), nullable=True),
    sa.Column('critic_tier', sa.VARCHAR(), nullable=True),
    sa.Column('last_score_sync', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_name', sa.VARCHAR(), nullable=False),
    sa.Column('access_token', sa.VARCHAR(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.drop_table('sync_history')
    op.drop_table('oauth_tokens_v2')
    op.drop_table('maintenance_logs')
    with op.batch_alter_table('game_cache_v2', schema=None) as batch_op:
        batch_op.drop_index('idx_title')
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_release_date')
        batch_op.drop_index('idx_platform_type')
        batch_op.drop_index('idx_ltf')
        batch_op.drop_index('idx_game_type')
        batch_op.drop_index('idx_expiry')

    op.drop_table('game_cache_v2')
    op.drop_table('api_limits_v2')
    # ### end Alembic commands ###
