"""add_tiktok_id

Revision ID: c2c1070327e3
Revises: 8f0eec4d9375
Create Date: 2026-05-02 09:13:55.890069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c1070327e3'
down_revision: Union[str, Sequence[str], None] = '8f0eec4d9375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.create_unique_constraint('uq_user_tiktok_id', ['tiktok_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
