STRINGS = {
    'en': {
        'welcome': "🎮 <b>Welcome to Game Alert!</b> 🎮\n\nI'm your ultimate gaming companion. I'll alert you about:\n📅 <b>Upcoming Releases</b>\n🎁 <b>Free Games</b>\n⚠️ <b>Games Leaving Subscriptions</b>\n\n⚙️ Use /settings to customize your preferences.\n\n<b>Commands:</b>\n🚀 /upcoming - View upcoming releases\n🎁 /free - View current free games\n⏳ /leaving - View games leaving services\n🌐 /language - Change language",
        'start_hint': "Try plain text like <b>free PC strategy</b>, <b>new mobile games</b>, <b>best RPG</b>, or <b>more like Hades</b>.",
        'help_text': "🎮 <b>Game Alert help</b>\n\n/recommend free PC strategy\n/free mobile\n/mobile\n/upcoming\n/search Zelda\n/profile\n/watchlist\n/settings\n\nYou can also type naturally: <i>best free games ending soon</i>.",
        'no_free_games': "😔 <i>No free games found at the moment. Check back later!</i>",
        'current_free': "🎁 <b>Current Free Games:</b>",
        'no_upcoming': "😔 <i>No upcoming releases found or API key is missing.</i>",
        'upcoming_releases': "🚀 <b>Upcoming Releases (Next 7 Days):</b>",
        'no_leaving': "✅ <i>No games leaving soon.</i>",
        'leaving_soon': "⚠️ <b>Games Leaving Soon:</b>",
        'settings_title': "⚙️ <b>Settings</b>\n<i>Customize what notifications you receive:</i>",
        'settings_first': "Please use /start first so I can create your profile.",
        'daily_releases': "📅 Daily Releases",
        'free_games': "🎁 Free Games",
        'leaving_games': "⚠️ Leaving Games",
        'platform': "🕹️ Platform",
        'value': "💰 Value",
        'free': "🆓 FREE",
        'end_date': "⏳ End Date",
        'claim_here': "👉 Claim here",
        'release_date': "📅 Release Date",
        'coming_in': "⏳ Coming in",
        'days': "days",
        'hours': "hours",
        'platforms': "🕹️ Platforms",
        'leaving': "🛑 Leaving",
        'date': "🗓️ Date",
        'language': "🌐 Language",
        'change_language': "🌐 <b>Select your language:</b>",
        'lang_en': "English 🇬🇧",
        'lang_ar': "العربية 🇸🇦",
        'search_usage': "🔍 <b>Usage:</b> /search [game name]",
        'searching': "🔍 <i>Searching for game...</i>",
        'not_found': "😔 <i>Game not found.</i>",
        'db_error': "⚠️ I could not read the game database right now. Please try again shortly.",
        'rating': "Rating",
        'stats_text': "📊 <b>Game Alert Statistics:</b>\n👥 Total Users: {users}",
        'free_title': "Free games available",
        'free_page_status': "{total} games found | Page {page} of {total_pages}",
        'free_filter_hint': "Filter",
        'free_empty': "😔 <b>No free games are active right now.</b>\n\nThe bot checks sources in the background. Try again later or use /upcoming.",
        'free_empty_filtered': "😔 <b>No free games match this view right now.</b>\n\nRemove the platform/source filter or try /free.",
        'free_error': "⚠️ I could not load free games right now. Please try again shortly.",
        'free_platform': "Platform",
        'free_source': "Source",
        'free_expires': "Ends",
        'free_open': "Open deal",
        'free_refresh': "Refresh",
        'free_previous': "Previous",
        'free_next': "Next",
        'free_all': "All",
        'free_controls': "Choose a filter or page:",
        'stale_button': "That button is out of date. Reloading the latest view.",
        'pc': "PC",
        'ps': "PlayStation",
        'xbox': "Xbox",
        'switch': "Nintendo Switch",
        'mobile': "Mobile 📱",
        'back': "⬅️ Back",
        'menu_recommend': "Recommend",
        'menu_free': "Free games",
        'menu_upcoming': "Upcoming",
        'menu_mobile': "Mobile",
        'menu_profile': "Profile",
        'menu_help': "Help",
        'menu_settings': "Settings",
        'recommend_title': "🎯 <b>Recommended for you</b>",
        'recommend_empty': "I could not find a good match yet. Try a platform, genre, store, or budget.",
        'recommend_error': "⚠️ Recommendations are unavailable right now. Please try again shortly.",
        'recommend_prompt': "Tell me what you want to play: free PC strategy, best RPG, new mobile games, or ألعاب مجانية.",
        'quick_upcoming': "Use /upcoming for the latest release list.",
        'quick_settings': "Use /settings to change notification preferences.",
        'quick_mobile': "Opening mobile game picks.",
        'why_this': "Why",
        'balanced_reason': "balanced freshness, quality, and your preferences",
        'free_recommend_intro': "🎁 <b>Free picks worth checking now</b>",
        'mobile_recommend_intro': "📱 <b>Mobile picks for you</b>",
        'upcoming_recommend_intro': "🚀 <b>Upcoming games to watch</b>",
        'quality_recommend_intro': "🏆 <b>Higher-rated picks</b>",
        'similar_recommend_intro': "🎯 <b>More like that</b>",
        'more_like_this': "More like this",
        'next_pick': "Next picks",
        'higher_rated': "Higher rated",
        'ending_soon': "Ending soon",
        'like': "👍 Like",
        'dislike': "👎 Not for me",
        'watchlist': "⭐ Save",
        'watchlist_title': "⭐ <b>Your saved games</b>",
        'watchlist_empty': "Your saved list is empty. Tap ⭐ Save on a game to build it.",
        'profile_title': "🧠 <b>Your game profile</b>",
        'profile_summary': "🧠 <b>Your game profile</b>\nPlatforms: {platforms}\nStores: {sources}\nGenres/signals: {genres}\nLikes: {likes} | Saved: {watchlist} | Dislikes: {dislikes}",
        'profile_empty': "I am still learning. Like, save, dislike, or ask for games by genre/platform to build your profile.",
        'preferences_reset': "Your learned game preferences were reset.",
        'feedback_like': "👍 Got it. I will use this to improve your recommendations.",
        'feedback_dislike': "👎 Got it. I will avoid similar picks.",
        'feedback_watchlist': "⭐ Saved to your preference profile.",
    },
    'ar': {
        'welcome': "🎮 <b>مرحباً بك في Game Alert!</b> 🎮\n\nأنا رفيقك المثالي في عالم الألعاب. يمكنني إعلامك بـ:\n📅 <b>أحدث إصدارات الألعاب</b>\n🎁 <b>الألعاب المجانية الحصرية</b>\n⚠️ <b>الألعاب التي ستغادر خدمات الاشتراك</b>\n\n⚙️ استخدم /settings لتخصيص إشعاراتك كما تحب.\n\n<b>الأوامر المتاحة:</b>\n🚀 /upcoming - عرض الإصدارات القادمة\n🎁 /free - اكتشاف الألعاب المجانية\n🔍 /search - البحث عن لعبة\n⏳ /leaving - عرض الألعاب المغادرة قريباً\n🌐 /language - تغيير لغة البوت",
        'start_hint': "جرّب كتابة طلب طبيعي مثل <b>ألعاب مجانية للكمبيوتر</b> أو <b>ألعاب جوال جديدة</b> أو <b>أفضل RPG</b>.",
        'help_text': "🎮 <b>مساعدة Game Alert</b>\n\n/recommend ألعاب مجانية للكمبيوتر\n/free mobile\n/mobile\n/upcoming\n/search Zelda\n/profile\n/watchlist\n/settings\n\nتقدر تكتب بشكل طبيعي: <i>أفضل ألعاب مجانية قبل ما تنتهي</i>.",
        'no_free_games': "😔 <i>عذراً، لا توجد ألعاب مجانية متاحة حالياً. عد لاحقاً!</i>",
        'current_free': "🎁 <b>أحدث الألعاب المجانية المتاحة:</b>",
        'no_upcoming': "😔 <i>لم نتمكن من العثور على إصدارات قادمة. (تأكد من إعداد مفتاح API)</i>",
        'upcoming_releases': "🚀 <b>أبرز الإصدارات خلال الـ 7 أيام القادمة:</b>",
        'no_leaving': "✅ <i>لا توجد ألعاب ستغادر الخدمات قريباً، يمكنك اللعب باطمئنان!</i>",
        'leaving_soon': "⚠️ <b>ألعاب ستغادر قريباً (سارع بتجربتها):</b>",
        'settings_title': "⚙️ <b>إعدادات الإشعارات</b>\n<i>تحكم فيما تريد أن نرسله إليك:</i>",
        'settings_first': "استخدم /start أولاً حتى أنشئ ملفك.",
        'daily_releases': "📅 الإصدارات اليومية",
        'free_games': "🎁 الألعاب المجانية",
        'leaving_games': "⚠️ الألعاب المغادرة",
        'platform': "🕹️ المنصة",
        'value': "💰 القيمة السابقة",
        'free': "🆓 مجاناً الآن",
        'end_date': "⏳ ينتهي العرض في",
        'claim_here': "👉 احصل عليها من هنا",
        'release_date': "📅 تاريخ الإصدار",
        'coming_in': "⏳ موعدنا بعد",
        'days': "أيام",
        'hours': "ساعة",
        'platforms': "🕹️ المنصات المدعومة",
        'leaving': "🛑 الخدمة المغادرة",
        'date': "🗓️ التاريخ المتوقع",
        'language': "🌐 لغة البوت",
        'change_language': "🌐 <b>الرجاء اختيار لغتك المفضلة:</b>",
        'lang_en': "English 🇬🇧",
        'lang_ar': "العربية 🇸🇦",
        'search_usage': "🔍 <b>طريقة البحث:</b> /search [اسم اللعبة]",
        'searching': "🔍 <i>جاري البحث عن اللعبة...</i>",
        'not_found': "😔 <i>لم يتم العثور على اللعبة.</i>",
        'db_error': "⚠️ تعذر قراءة قاعدة بيانات الألعاب الآن. حاول بعد قليل.",
        'rating': "التقييم",
        'stats_text': "📊 <b>إحصائيات Game Alert:</b>\n👥 إجمالي المستخدمين: {users}",
        'free_title': "الألعاب المجانية المتاحة",
        'free_page_status': "تم العثور على {total} ألعاب | الصفحة {page} من {total_pages}",
        'free_filter_hint': "التصفية",
        'free_empty': "😔 <b>لا توجد ألعاب مجانية نشطة حالياً.</b>\n\nيتحقق البوت من المصادر في الخلفية. حاول لاحقاً أو استخدم /upcoming.",
        'free_empty_filtered': "😔 <b>لا توجد ألعاب مجانية تطابق هذا العرض حالياً.</b>\n\nأزل تصفية المنصة/المصدر أو استخدم /free.",
        'free_error': "⚠️ تعذر تحميل الألعاب المجانية الآن. حاول مرة أخرى بعد قليل.",
        'free_platform': "المنصة",
        'free_source': "المصدر",
        'free_expires': "ينتهي",
        'free_open': "فتح العرض",
        'free_refresh': "تحديث",
        'free_previous': "السابق",
        'free_next': "التالي",
        'free_all': "الكل",
        'free_controls': "اختر تصفية أو صفحة:",
        'stale_button': "هذا الزر قديم. سأعيد تحميل أحدث عرض.",
        'no_mobile_games': "😔 <i>عذراً، لا توجد توصيات لألعاب الجوال حالياً.</i>",
        'mobile_hot': "🔥 <b>أبرز توصيات ألعاب الجوال:</b>",
        'pc': "كمبيوتر (PC)",
        'ps': "بلايستيشن",
        'xbox': "إكس بوكس",
        'switch': "نينتندو سويتش",
        'mobile': "الجوال 📱",
        'back': "⬅️ عودة",
        'menu_recommend': "ترشيحات",
        'menu_free': "ألعاب مجانية",
        'menu_upcoming': "قادمة",
        'menu_mobile': "الجوال",
        'menu_profile': "ملفي",
        'menu_help': "مساعدة",
        'menu_settings': "الإعدادات",
        'recommend_title': "🎯 <b>ترشيحات مناسبة لك</b>",
        'recommend_empty': "لم أجد ترشيحاً مناسباً الآن. جرّب منصة أو نوع لعبة أو متجر أو ميزانية.",
        'recommend_error': "⚠️ الترشيحات غير متاحة حالياً. حاول لاحقاً.",
        'recommend_prompt': "اكتب ما تريد لعبه مثل: ألعاب مجانية للكمبيوتر، أفضل RPG، ألعاب جوال جديدة.",
        'quick_upcoming': "استخدم /upcoming لعرض أحدث الإصدارات القادمة.",
        'quick_settings': "استخدم /settings لتعديل تفضيلات الإشعارات.",
        'quick_mobile': "هذه ترشيحات ألعاب الجوال.",
        'why_this': "سبب الترشيح",
        'balanced_reason': "توازن بين الحداثة والجودة وتفضيلاتك",
        'free_recommend_intro': "🎁 <b>ألعاب مجانية تستحق التجربة الآن</b>",
        'mobile_recommend_intro': "📱 <b>ترشيحات ألعاب جوال مناسبة لك</b>",
        'upcoming_recommend_intro': "🚀 <b>ألعاب قادمة تستحق المتابعة</b>",
        'quality_recommend_intro': "🏆 <b>ترشيحات بتقييم أعلى</b>",
        'similar_recommend_intro': "🎯 <b>ألعاب مشابهة</b>",
        'more_like_this': "مشابهة",
        'next_pick': "ترشيحات أخرى",
        'higher_rated': "تقييم أعلى",
        'ending_soon': "تنتهي قريباً",
        'like': "👍 أعجبني",
        'dislike': "👎 لا يناسبني",
        'watchlist': "⭐ حفظ",
        'watchlist_title': "⭐ <b>ألعابك المحفوظة</b>",
        'watchlist_empty': "قائمتك فارغة. اضغط ⭐ حفظ على أي لعبة لبناء قائمتك.",
        'profile_title': "🧠 <b>ملف تفضيلاتك</b>",
        'profile_summary': "🧠 <b>ملف تفضيلاتك</b>\nالمنصات: {platforms}\nالمتاجر: {sources}\nالأنواع/الإشارات: {genres}\nإعجابات: {likes} | محفوظة: {watchlist} | غير مناسبة: {dislikes}",
        'profile_empty': "ما زلت أتعلم تفضيلاتك. اضغط أعجبني أو حفظ أو لا يناسبني أو اطلب ألعاباً حسب النوع/المنصة.",
        'preferences_reset': "تم مسح تفضيلات الألعاب المتعلّمة.",
        'feedback_like': "👍 تم. سأستخدم هذا لتحسين الترشيحات القادمة.",
        'feedback_dislike': "👎 تم. سأتجنب الترشيحات المشابهة.",
        'feedback_watchlist': "⭐ تم حفظها في ملف تفضيلاتك.",
    }
}

def get_string(lang, key):
    return STRINGS.get(lang, STRINGS['ar']).get(key, STRINGS['ar'].get(key, key))


def format_string(lang, key, **kwargs):
    return get_string(lang, key).format(**kwargs)
